### ISSUE TITLE
Add LV2 to all OS targets

### ISSUE THREAD

**Issue by dromer** [cvde/RoomReverb#1]
I saw that you added LV2 builds for Linux, this is great!

However LV2 is a fully cross-platform format and JUCE7 afaik also supports it for Windows and MacOS.
Please also enable it for these other Operating Systems.

cheers

**Comment by cvde** [comment]
I wasn't aware that LV2 is a thing on Win/Mac. Thanks for the hint!

**Comment by dromer** [comment]
Oh yeah it's 100% cross-platform. Also runs on the *BSDs and Haiku and stuff ;)

Some modern hosts that support it: Reaper, Ardour, Mixbus, Carla, Mixxx, Zrythm, and of course JUCE7 itself (I'm probably forgetting some, but these are the more prominent ones)

**Comment by cvde** [comment]
LV2 is now also available on Windows & Mac!
