### ISSUE TITLE
Should I be able to compile fv3 on ARM64?

### ISSUE THREAD

**Issue by cristianvogel** [cvde/RoomReverb#5]
Hi,

Love your reverbs. Wanted to try them out in another context, but I just have linker errors 

`Undefined symbols for architecture arm64:
  "fv3::allpass2_f::~allpass2_f()", referenced from:
      fv3::progenitor_f::~progenitor_f() in libNEL_scape_space__v0.8.7-beta_SharedCode.a(RoomReverb.cpp.o)
`

etc... Any pointers would be useful. Thanks!

**Comment by cvde** [comment]
Hi,
yes, fv3 can be compiled on ARM64 (I actually developed the plugin on ARM64).
I close the issue as I cannot provide fv3 support here.
